name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        pymongo-version: ["4.0", "4.2", "4.3"]
        mongodb-version: ["4.4", "5.0", "6.0"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Run test
        run: |
          python -m pip install -U pip
          # Use tox-gh to configure the python environment
          # See https://github.com/tox-dev/tox-gh
          python -m pip install tox_gh pymongo==${{ matrix.pymongo-version }}
          tox
 
